-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."worker_sub_roles" add column "description" Text
--  not null;
