table:
  name: onboarding_application
  schema: public
object_relationships:
  - name: bluebee_user
    using:
      foreign_key_constraint_on: user_id
select_permissions:
  - role: user
    permission:
      columns:
        - completed
        - is_signup_completed
        - reference
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - is_signup_completed
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
