-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO vaccine(name)
-- VALUES
-- ('Td/IPV (Tetanus/Diphtheria/Polio)'),
-- ('HPV Vaccination'),
-- ('MMR Vaccination'),
-- ('Hepatitis B Vaccination'),
-- ('Flu Vaccination'),
-- ('BCG Vaccination'),
-- ('COVID-19 Booster'),
-- ('COVID-19 2nd Dose'),
-- ('COVID-19 1st Dose');
