-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO worker_policy(name, tally_form_id)
-- VALUES
-- ('Alcohol, Smoking and Drug Use Policy','mRG9DK'),
-- ('Dismissal Appeals Policy','wobj2b'),
-- ('Induction Training Policy','nGxPRe'),
-- ('Staff Qualities and Qualifications Policy','mVL6zj'),
-- ('Bring Your Own Device (BYOD) Policy','nPdqz1'),
-- ('DBS Handling and Security Disclosure Information Policy','3EkOxl'),
-- ('Dress Code and Uniforms Policy','3jaVlQ'),
-- ('Equal Opportunities Policy','3lbEOo'),
-- ('Discloure and Barring (DBS) Procedure','w44bKr'),
-- ('Whistleblowing Policy','mD4Gpl'),
-- ('Bullying and Harassment Policy','3Np1ZQ'),
-- ('Recruitment Policy','3NpZpN'),
-- ('Health and Safety Risk Assessment Policy','nrjZjp');
