-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."client_invoice" add column "stripe_payment_id" text
--  null unique;
