-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO worker_training(name, description)
-- VALUES
-- ('COSHH Awareness',''),
-- ('Dementia Awareness', ''),
-- ('End of Care', ''),
-- ('Equality & Diversity', ''),
-- ('Fire Safety', ''),
-- ('Fire Marshal', ''),
-- ('First Aid', ''),
-- ('Food Hygiene', ''),
-- ('GDPR Awareness', ''),
-- ('Health & Safety', ''),
-- ('Infection Control', ''),
-- ('Manual Handling', ''),
-- ('Medication Awareness', ''),
-- ('Mental Capacity Act & DOLS', ''),
-- ('Nutrition and Fluid', ''),
-- ('Person Centred Care', ''),
-- ('Safeguarding Adults at Risk', '');
