-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO payout_status(status)
-- VALUES
-- ('UNPAID'),
-- ('PENDING'),
-- ('PAID');
