-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."onboarding_application" add column "parsed_data" jsonb
--  null;
