-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."shift" add column "repeat_weekly" boolean
--  not null default 'false';
